name: pvapp_environment
channels:
  - defaults
dependencies:
  - python=3.12
  - altair==5.3.0
  - streamlit==1.33.0
  - pandas==2.2.2
  - requests==2.31.0
env_vars:
  LC_ALL: de_DE.UTF-8
  LANG: de_DE.UTF-8
